### TEST GET / WEBSITE
GET http://localhost:8080

### TEST GET /api/data
GET http://localhost:8080/api/data

### TEST POST adding a user

POST http://localhost:8080/api/data
Content-Type: application/json

{
    "name": "gargamel"
}

### TEST DELETE

DELETE http://localhost:8080/api/data