### TEST GET / WEBSITE
GET http://localhost:8080

### TEST GET TOOL

GET http://localhost:8080/api/tools/5
Content-Type: application/json
Authorization: Bearer <jwt token>


### TEST CREATE REQUEST
POST http://localhost:8080/api/requests
Content-Type: application/json
Authorization: Bearer <jwt token>

{
  "toolId": 8,
  "startDate": "2025-10-01T00:00:00.000Z",
  "endDate": "2025-10-05T00:00:00.000Z",
  "price": 200
}

### 2. Hämta alla requests jag skickat
GET http://localhost:8080/api/requests/sent
Content-Type: application/json
Authorization: Bearer <jwt token>

### 2. Hämta alla requests jag fått
GET http://localhost:8080/api/requests/recieved
Content-Type: application/json
Authorization: Bearer <jwt token>


### TEST LOGIN qwerty

POST http://localhost:8080/api/users/login
Content-Type: application/json

{
 "username": "",
 "password": ""
}

### TEST CREATE REQUEST qwerty
POST http://localhost:8080/api/requests
Content-Type: application/json
Authorization: Bearer <jwt-token>

{
  "toolId": 10,
  "startDate": "2025-10-01T00:00:00.000Z",
  "endDate": "2025-10-05T00:00:00.000Z",
  "price": 200
}

### Delete a request by id
DELETE http://localhost:8080/api/requests/1
Authorization: Bearer <jwt token>


### Update a request
PUT http://localhost:8080/api/requests/16
Authorization: Bearer <jwt-token>
Content-Type: application/json

{
  "pending": false,
  "accepted": false
}

### Get all bookings
GET http://localhost:8080/api/bookings
Authorization: Bearer <jwt-token>
Content-Type: application/json
